<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-15 10:41
=======
# Generated by Django 5.2 on 2025-04-12 12:19
>>>>>>> 402df49d1512256bdbdf3c525df5205b85c9a137

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerces', '0004_payment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerces.category'),
        ),
    ]
