<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-15 07:44
=======
# Generated by Django 5.2 on 2025-05-13 09:30
>>>>>>> e847b4f800bc0aa1111626ff99cc9e42211f2d2e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerces', '0018_alter_shop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
